export const RolSeeder = async(Model)=>{
    await Model.create({name:'Administrador'})
    await Model.create({name:'Chofer'})
}

export const ComponentsSeeder = async(Model) =>{
    await Model.create({name:'Listar-monitoreo'})
    await Model.create({name:'Listar-usuarios'})
    await Model.create({name:'Editar-usuarios'})
    await Model.create({name:'Eliminar-usuarios'})
    await Model.create({name:'Crear-usuarios'})
    await Model.create({name:'Detalles-usuarios'})
    await Model.create({name:'Listar-rol'})
    await Model.create({name:'Editar-rol'})
    await Model.create({name:'Eliminar-rol'})
    await Model.create({name:'Crear-rol'})
    await Model.create({name:'Agregar-rol'})
    await Model.create({name:'Quitar-rol'})
    await Model.create({name:'Listar-microbus'})
    await Model.create({name:'Editar-microbus'})
    await Model.create({name:'Eliminar-microbus'})
    await Model.create({name:'Crear-microbus'})
    await Model.create({name:'Detalles-microbus'})
    await Model.create({name:'Asignar_usuario-microbus'})
    await Model.create({name:'Listar-tarifa'})
    await Model.create({name:'Editar-tarifa'})
    await Model.create({name:'Eliminar-tarifa'})
    await Model.create({name:'Crear-tarifa'})
    await Model.create({name:'Listar-horario'})
    await Model.create({name:'Editar-horario'})
    await Model.create({name:'Eliminar-horario'})
    await Model.create({name:'Crear-horario'})
    await Model.create({name:'Listar-ruta'})
    await Model.create({name:'Editar-ruta'})
    await Model.create({name:'Eliminar-ruta'})
    await Model.create({name:'Crear-ruta'})
    await Model.create({name:'Listar-linea'})
    await Model.create({name:'Editar-linea'})
    await Model.create({name:'Eliminar-linea'})
    await Model.create({name:'Crear-Linea'})
    await Model.create({name:'Listar_horario-linea'})
    await Model.create({name:'Listar_tarifas-linea'})
    await Model.create({name:'Listar_buses-linea'})
    await Model.create({name:'Listar_rutas-linea'})
    await Model.create({name:'Listar_buses_rutas-linea'})
    await Model.create({name:'Asignar_ruta-linea'})
    await Model.create({name:'Asignar_bus-linea'})
    await Model.create({name:'Asignar_tarifas-linea'})
    await Model.create({name:'Asignar_horarios-linea'})
    await Model.create({name:'Listar-conexiones'})
}
